### PR TITLE
Full Port to 1.12.2 (WIP)

### PR DESCRIPTION
**Pull request by CDAGaming**
Completed Port for 1.12.2

- DO NOT MERGE YET; Need to apply 2nd MCP Mappings Update

### CODE REVIEW

**Comment by TehNut** [comment]
No this already runs on 1.12.2

**Comment by CDAGaming** [comment]
@TehNut Then why does it have dependencies that build on 1.12, some of which, the version of JEI shouldn't have even been able to work on 1.12.2?

This PR just makes it Officially run off of 1.12.2, and nothing more (Besides the MCP Mappings Update, and Removing an Unneeded line in Waila.java)

**Comment by TehNut** [comment]
The dependencies are compile time only. The mod runs perfectly fine on 1.12.2 with 1.12.2 JEI. You obviously do not understand how these dependencies work.

MCP mappings are source only and do not need to be constantly updated. 

That "unused" line is used at the start of new MC versions for minimum Forge requirements. I don't want to re-add it every time.

Every attempted change in this PR is something for project managers to do, not random people.

**Comment by CDAGaming** [comment]
Very well, i see your point on everything you mentioned except 2 things:


1) that the JEI version you target currently is
 A) An Alpha version on curseforge with numerous more stable versions ahead of it and 
 B) Does not even target 1.12.2 and doesn't even list that it supports it.

References:
https://minecraft.curseforge.com/projects/just-enough-items-jei/files/2442204 (What this repo Uses)
https://minecraft.curseforge.com/projects/just-enough-items-jei/files/2487152 (Minimum safest Release with confirmed compatibility for 1.12.2)

2) As for the second thing, i removed the line in Waila.java mainly because you never had specified minimum Forge Version to be used on that line. The other option for this PR i would've done there was just add "14.23.0.0" to the minimum version, so that all 1.12.2 version of forge may be used for this mod (Which is currently allowed) but also ensure no versions below that can run it, reducing possible user-error.

It's your call here on both these, but if you think it's ok to leave it as is, ill leave this be...

**Comment by TehNut** [comment]
>that the JEI version you target currently is
A) An Alpha version on curseforge with numerous more stable versions ahead of it and
B) Does not even target 1.12.2 and doesn't even list that it supports it.

I would like to point back to where I *Already covered this*.

>***The dependencies are compile time only.*** The mod runs perfectly fine on 1.12.2 with 1.12.2 JEI. You obviously do not understand how these dependencies work.

>As for the second thing, i removed the line in Waila.java mainly because you never had specified minimum Forge Version to be used on that line.

A recommended Forge build that works has been out for several months. There is no need to list one anymore.

**Pull request closed without merging**
