### PR TITLE
1.14 fabric update

### PR DESCRIPTION
**Pull request by MelanX**

### CODE REVIEW

**Comment by TehNut** [comment]
What's the point of this? Did something break requiring a recompilation?

**Comment by MelanX** [comment]
to be honestly.. I haven't checked.. xD sometimes I just do something and after this I think about it xD

**Comment by TehNut** [comment]
Unnecessary dependency bumps are useless and just cause me to needlessly refresh my workspace

**Comment by MelanX** [comment]
sorry :c

**Pull request closed without merging**
