### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by queengooborg**

### CODE REVIEW

**Comment by TehNut** [comment]
What adds this file and why can't you just manually ignore it? There's not really a reason to include this.

**Comment by queengooborg** [comment]
It's true, manually ignoring these types of files is possible, but at the same time if you forget to omit staging these files, it's possible to leak your login information.  .launch files are Eclipse run configuration files, which some modders may use their real account instead of a temporary testing account, which means that they add their email and password to the run configuration, which means they add it to the .launch files, which...well, you get the picture.  X3  So, why not automate the process?

(I also explained this on https://github.com/sk89q/WorldEdit/pull/386)

**Comment by ChloeDawn** [comment]
wat

**Comment by TehNut** [comment]
I still honestly don't see a reason to add it. Pay attention to what you commit.

**Comment by adrwa** [comment]
image

**Comment by TehNut** [comment]
I mean, if you had submitted this along with a proper fix for something, I'd pull it without question. But all you're doing is adding a single line to a `.gitignore`. You're not going to gain much traction with all this PR spam.

Sorry, I'm not going to pull this. Don't bother on any other projects I maintain, either.

**Comment by queengooborg** [comment]
That's completely fine, it's up to you whether or not you think it would be better to leave a security hole open for others or if you think this is a reasonable addition -- this is actually a very small update in a line of bug fixes I'm doing for mods (as well as for those that are out of date, port them to 1.11.2 unless otherwise requested by the mod devs) to increase compatibility, fill in information for users and developers alike, apply translations where needed, and more.

I'm really just trying to help out, you don't need to be impolite about it.  '^^

**Comment by TehNut** [comment]
>it's up to you whether or not you think it would be better to leave a security hole open for others

Wow that is a loaded and very passive aggressive sentence. Again, it's on you if you store your login information *in plaintext*. Don't do that. If you need a stable username/uuid between launches, just use `--username=WhateverYouWant` as your launch arg.

>you don't need to be impolite about it. '^^

I wasn't impolite in the slightest. I explained *why* I wasn't going to pull it.

**Comment by queengooborg** [comment]
I'm referring to "Don't bother on any other projects I maintain, either" in particular.  I understand why you're not merging this PR, and I agree that it's a horrible decision to set the `--password` launch option (which, unfortunately, I've seen many people do, and sometimes it's needed such as if you're trying something out on a public server), an option I'm definitely staying away from.

Nevertheless, I'll still be doing the bug fixes and fill in any missing information/translations/etc. where needed, and submit a pull request for those changes, unless you specifically request me not to, alright?

**Comment by TehNut** [comment]
I'm fine with content PRs. And when I said to not open it on my other projects, I meant *this* specific PR. Like, don't go to Blood Magic adding `.launch` to the `.gitignore` (I think it already is tbh) without any proper meat to the it.

**Comment by queengooborg** [comment]
That's where I misinterpreted your response -- I assumed that you meant that you didn't want me to submit pull requests about anything, not just adding to the .gitignore.  That's completely alright, I can understand how you feel about having a pull request with just a single change such as this (which I found out that a bunch of pull requests were automatically sent to a bunch of other repositories owned by other developers, it's going to take a while to take care of all of those... -_-).  I'll submit that new PR for the other things when it's all ready to go, which I hope you enjoy, kay?

**Comment by dshadowwolf** [comment]
I'm going to try and be as diplomatic as possible: When submitting PR's and expecting the person controlling the repository and project to take you seriously, you do not argue with them when they say "No", no matter how bad you, personally, think their reasons are or for any other reason.

By doing such you are showing a lack of respect for the person/people in charge and, to me, a lack of maturity. Now... I can't tell Nut what to do, but I can tell you that, were you to do this to me, I'd refuse any submissions by you to the project and seriously consider blocking you from the project altogether.

Anyway, take my advice, don't take it - I really don't give a shit. My goal here was to try and educate a younger person on the realities of the world and working on open source projects. Actually listening and deciding if the advice is right is up to the other side.

**Comment by queengooborg** [comment]
But, I...wasn't arguing when they said "no" to the pull request, @dshadowwolf.  I'm not going to try to push my will on anyone as it does nothing but cause problems.  Sharing my point of view, yes, I'll do, but when someone says "no" for an answer, I understand and respect that it means "no."  I'm not just going to submit the same change over and over again and argue that it has to be pulled, because all that does is frustrate the project managers and get my account flagged or even terminated for spamming.

**Pull request closed without merging**
