### PR TITLE
Port to 1.16.1 Forge with Better Mappings.

### PR DESCRIPTION
**Pull request by MoreThanHidden**
Reverted changes in #265 due to missing mappings.

### CODE REVIEW

**Comment by TehNut** [comment]
Are `ITextComponent` methods seriously still not mapped? Just how slow is MCP nowadays?

**Comment by MoreThanHidden** [comment]
I have a my own mappings with it but this is the latest one on the forge repo, MCPBot isn't maintained so guess they are trying to get mms completed.

**Comment by Shadows-of-Fire** [comment]
The option to used yarn-mixed mappings exists now (`20200723-mixed-1.16.1`), which should allow for (mostly) everything to be mapped properly.

**Comment by TehNut** [comment]
The hack for displaying the config GUI isn't necessary anymore as of https://github.com/MinecraftForge/MinecraftForge/pull/6208, but I can take care of moving it over to that.

If you're happy with the current state, I'll merge this and get a release out tonight.

**Pull request merged**
