### PR TITLE
Update to 1.15.1 (Fabric)

### PR DESCRIPTION
**Pull request by l2dy**

### CODE REVIEW

**Comment by TehNut** [comment]
Does it not run on 1.15.1?

**Comment by l2dy** [comment]
It does. I'm just trying to update `mc_version` to 1.15.1.

**Comment by jellonek** [comment]
Does it require pluginloader on 1.15.1? If so - in which version?

**Comment by l2dy** [comment]
Fixed in 5ebc89b30be3e44954a50721633a54b4a94feeb0.

**Pull request closed without merging**
